// This file is part of minilib, (c) 2012-2019 Michael Misc Myer.
// misc.myer@zoho.com / www.github.com/michael105
// Licensed under BSD License.
// Please see the files LICENSE and NOTICE for the exact conditions. 



// Everything below will be silently overwritten,
// when make header ist invoked

// --- define_macros-start: generate --- //
#define memfrob(...) _M_MLIB_memfrob_M_()
#define fgetpos(...) _M_MLIB_fgetpos_M_()
#define fileno(...) _M_MLIB_fileno_M_()
#define dup3(...) _M_MLIB_dup3_M_()
#define strcmp(...) _M_MLIB_strcmp_M_()
#define fclose(...) _M_MLIB_fclose_M_()
#define close(...) _M_MLIB_close_M_()
#define isprint(...) _M_MLIB_isprint_M_()
#define snprintf(...) _M_MLIB_snprintf_M_()
#define creat(...) _M_MLIB_creat_M_()
#define stat(...) _M_MLIB_stat_M_()
#define strncpy(...) _M_MLIB_strncpy_M_()
#define def(...) _M_MLIB_def_M_()
#define itohex(...) _M_MLIB_itohex_M_()
#define sprintf(...) _M_MLIB_sprintf_M_()
#define mprotect(...) _M_MLIB_mprotect_M_()
#define getcwd(...) _M_MLIB_getcwd_M_()
#define strerror(...) _M_MLIB_strerror_M_()
#define rand(...) _M_MLIB_rand_M_()
#define ftruncate(...) _M_MLIB_ftruncate_M_()
#define dtodec(...) _M_MLIB_dtodec_M_()
#define unlink(...) _M_MLIB_unlink_M_()
#define write(...) _M_MLIB_write_M_()
#define _itohex(...) _M_MLIB__itohex_M_()
#define getenv(...) _M_MLIB_getenv_M_()
#define dup2(...) _M_MLIB_dup2_M_()
#define getpid(...) _M_MLIB_getpid_M_()
#define fsetpos(...) _M_MLIB_fsetpos_M_()
#define fstat(...) _M_MLIB_fstat_M_()
#define free(...) _M_MLIB_free_M_()
#define read(...) _M_MLIB_read_M_()
#define printf(...) _M_MLIB_printf_M_()
#define memcmp(...) _M_MLIB_memcmp_M_()
#define fprintf(...) _M_MLIB_fprintf_M_()
#define puts(...) _M_MLIB_puts_M_()
#define dup(...) _M_MLIB_dup_M_()
#define feof(...) _M_MLIB_feof_M_()
#define fputc(...) _M_MLIB_fputc_M_()
#define rename(...) _M_MLIB_rename_M_()
#define ftell(...) _M_MLIB_ftell_M_()
#define fopen(...) _M_MLIB_fopen_M_()
#define srand(...) _M_MLIB_srand_M_()
#define time(...) _M_MLIB_time_M_()
#define open(...) _M_MLIB_open_M_()
#define itodec(...) _M_MLIB_itodec_M_()
#define _itobin(...) _M_MLIB__itobin_M_()
#define tcgetattr(...) _M_MLIB_tcgetattr_M_()
#define memcpy(...) _M_MLIB_memcpy_M_()
#define memset(...) _M_MLIB_memset_M_()
#define strlen(...) _M_MLIB_strlen_M_()
#define vsnprintf(...) _M_MLIB_vsnprintf_M_()
#define putchar(...) _M_MLIB_putchar_M_()
#define printl(...) _M_MLIB_printl_M_()
#define gettimeofday(...) _M_MLIB_gettimeofday_M_()
#define ioctl(...) _M_MLIB_ioctl_M_()
#define rewind(...) _M_MLIB_rewind_M_()
#define strcpy(...) _M_MLIB_strcpy_M_()
#define dprintf(...) _M_MLIB_dprintf_M_()
#define strcat(...) _M_MLIB_strcat_M_()
#define atoi(...) _M_MLIB_atoi_M_()
#define lseek(...) _M_MLIB_lseek_M_()
#define fseek(...) _M_MLIB_fseek_M_()
#define fsync(...) _M_MLIB_fsync_M_()
#define fwrite(...) _M_MLIB_fwrite_M_()
#define fread(...) _M_MLIB_fread_M_()
#define tcsetattr(...) _M_MLIB_tcsetattr_M_()
#define fputs(...) _M_MLIB_fputs_M_()
#define isspace(...) _M_MLIB_isspace_M_()
#define malloc(...) _M_MLIB_malloc_M_()
#define uitodec(...) _M_MLIB_uitodec_M_()
#define select(...) _M_MLIB_select_M_()
#define print(...) _M_MLIB_print_M_()
#define strncmp(...) _M_MLIB_strncmp_M_()
#define itoHEX(...) _M_MLIB_itoHEX_M_()
// --- define_macros-end: generate --- //
