// generated by make header. 
// all macros and functions, defined by minilib.
// intended to be parsed by syntaxcheck plugins
#ifndef MLIB
#ifndef included_minilib_h
#define dirbufsize 2048
#define scandir_bufsize 4096
void optimization_fence(void*p);
#define asm(...)



static void* __attribute__((optimize("O0"))) mmap(void* addr, long len, int prot, int flags, int fd, off_t off){}
static void* sbrk(long incr){}
static inline int fgetc(FILE *F){}
static int fileno(FILE *F){}
#endif
#endif

