.\" sissylog.8
.\" wcm, 2009.09.29 - 2011.02.01
.\" ===
.TH sissylog 8 "January 2013" "perp-2.07" "persistent process supervision"
.SH NAME
sissylog \- log stdin to
.BR syslog (3)
.SH SYNOPSIS
.B sissylog [\-hV] [
.I ident
.B [
.I facility
.B ]]
.SH DESCRIPTION
.B sissylog
reads lines from standard input and writes them to the system logger with
.BR syslog (3).
.PP
If an
.I ident
argument is specified,
.B sissylog
prepends log entries accordingly.
Otherwise, entries are prepended with the identity string
``sissylog''.
.PP
If a
.I facility
argument is specified,
it should be in the form of a string selected from the following list:
.BR LOG_AUTH ,
.BR LOG_CRON ,
.BR LOG_DAEMON ,
.BR LOG_FTP ,
.BR LOG_KERN ,
.BR LOG_LPR ,
.BR LOG_MAIL ,
.BR LOG_NEWS ,
.BR LOG_SYSLOG ,
.BR LOG_USER ,
or
.BR LOG_UUCP .
.B sissylog
will use a corresponding facility argument with
.BR openlog (8).
If the 
.I facility
argument is not specified or not recognized,
.B sissylog
will use the facility
.B LOG_DAEMON
by default.
.PP
.B sissylog
inspects the beginning of each line for
.BR alert: ,
.BR error: ,
.BR warning: ,
.BR notice: ,
or
.BR debug: ,
and sets the priority of each log entry accordingly.
Otherwise, entries are made with the
.B LOG_INFO
priority by default.
.PP
.B sissylog
splits lines longer than 800 characters,
prepending continued lines with a `+' character.
.B sissylog
does not log empty lines,
and converts unprintable control characters to `?'.
.SH OPTIONS
.TP
.B \-h
Help.
Print a brief usage message to stderr and exit.
.TP
.B \-V
Version.
Print the version number to stderr and exit.
.SH SEE ALSO
.nh
.BR openlog(3),
.BR syslog(3),
.BR perp_intro (8),
.BR perpboot (8),
.BR perpctl (8),
.BR perpd (8),
.BR perpetrate (5),
.BR perphup (8),
.BR perpls (8),
.BR perpok (8),
.BR perpstat (8),
.BR tinylog (8)
.\" EOF sissylog.8
