#!/bin/sh
#
# A simple script to reset the scrolling regions of a vt100 terminal
#
# 'echo' must be able to understand octal escape sequences.

if [ "$BASH" ]; then
	echo -e "\033[m\033[;r\033[;H\033[2J"
else
	echo "\033[m\033[;r\033[;H\033[2J"
fi
