#ifndef linux_x64_allheaders_h\n#define linux_x64_allheaders_h
#include "./sys/syscall.h"
#include "./sys/utsname.h"
#include "./sys/signal.h"
#include "./sys/prctl.h"
#include "./sys/socket.h"
#include "./reboot.h"
#include "./bits/limits.h"
#include "./bits/stat.h"
#include "./bits/inotify.h"
#include "./bits/types.h"
#include "./mount.h"
#include "./fcntl.h"
#include "./seccomp.h"
#endif
