// Header generated by tools/genheaders.pl
// Put changes into ctype.h.in

#ifndef header_ctype_h
#define header_ctype_h

// file: include/isprint.h
static inline int __attribute__((always_inline)) isprint(const char c);

// file: src/isspace.c
int isspace(int c);



#include "include/minilib_global.h"


#ifdef mini_INCLUDESRC

#include "include/isprint.h"
#include "src/isspace.c"

// Need global included. Doesn't matter by which file.
#include "src/minilib_global.c"

// Need start.c included. Doesn't matter by which file.
#include "asm/start.c"

#endif

#endif
