// Header generated by tools/genheaders.pl
// Put changes into stdio.h.in

#ifndef header_stdio_h
#define header_stdio_h

// file: include/fputc.h
static inline int volatile fputc(int c, int fd);

// file: include/fputs.h
static inline int volatile fputs(const char *c, int fd);

// file: src/mfprintf.c
int fprintf(int fd, const char* fmt, ... );

// file: src/msprintf.c
int sprintf(char *buf, const char* fmt, ... );



#include "include/minilib_global.h"


#ifdef mini_INCLUDESRC

#include "include/fputc.h"
#include "include/fputs.h"
#include "src/msprintf.c"
#include "src/mfprintf.c"

// Need global included. Doesn't matter by which file.
#include "src/minilib_global.c"

// Need start.c included. Doesn't matter by which file.
#include "asm/start.c"

#endif

#endif
