// Header generated by tools/genheaders.pl
// Put changes into stdlib.h.in

#ifndef header_stdlib_h
#define header_stdlib_h

// file: src/atoi.c
int atoi(char *c);

// file: src/malloc.c
void* malloc(int size);

// file: src/malloc.c
void free(void *p);

// file: src/malloc.c
void* volatile malloc(int size);

// file: src/malloc.c
void volatile free(void* p);



#include "include/minilib_global.h"


#ifdef mini_INCLUDESRC

#include "src/malloc.c"
#include "src/atoi.c"

// Need global included. Doesn't matter by which file.
#include "src/minilib_global.c"

// Need start.c included. Doesn't matter by which file.
#include "asm/start.c"

#endif

#endif
