// Header generated by tools/genheaders.pl
// Put changes into string.h.in

#ifndef header_string_h
#define header_string_h

// file: src/memcpy.c
void *memcpy( void *d, const void *s, int n );

// file: src/memcpy.c
char *strcpy(char *dest, const char *src);

// file: src/memcpy.c
char *strncpy(char *dest, const char *src, int n);

// file: src/memset.c
void *memset( void *s, int c, int n);

// file: src/mstrcmp.c
int strcmp(const char*c1,const char*c2);

// file: src/mstrcmp.c
int strncmp(const char*c1,const char*c2,int len);

// file: src/mstrcmp.c
int memcmp(const void* c1,const void* c2,int len);

// file: src/mstrlen.c
int strlen(const char*str);

// file: src/strcat.c
char *strcat(char *dest, const char *src );



#include "include/minilib_global.h"


#ifdef mini_INCLUDESRC

#include "src/strcat.c"
#include "src/memcpy.c"
#include "src/mstrlen.c"
#include "src/memset.c"
#include "src/mstrcmp.c"

// Need global included. Doesn't matter by which file.
#include "src/minilib_global.c"

// Need start.c included. Doesn't matter by which file.
#include "asm/start.c"

#endif

#endif
