:hardbreaks:
==  Ansi C89


____
Scratched this from the ansi-c89 draft. +
Storing it here for reference.
____



=== functions/headers


==== ERRORS <errno.h>

     x    EDOM
     x    ERANGE
     x    errno


==== COMMON DEFINITIONS <stddef.h>

     x    NULL
         offsetof( type,  member-designator)
         ptrdiff_t
     x    size_t
     x    wchar_t


==== DIAGNOSTICS <assert.h>

         NDEBUG
         void assert(int expression);


==== CHARACTER HANDLING <ctype.h>

     x    int isalnum(int c);
     x    int isalpha(int c);
     x    int iscntrl(int c);
     x    int isdigit(int c);
     x    int isgraph(int c);
     x    int islower(int c);
     x    int isprint(int c); 
     x    int ispunct(int c);
     x    int isspace(int c); 
     x    int isupper(int c);
     x    int isxdigit(int c);
     x    int tolower(int c);
     x    int toupper(int c);


==== LOCALIZATION <locale.h>

         LC_ALL
         LC_COLLATE
         LC_CTYPE
         LC_MONETARY
         LC_NUMERIC
         LC_TIME
      x   NULL
         struct lconv
         char *setlocale(int category, const char *locale);
         struct lconv *localeconv(void);


==== MATHEMATICS <math.h>

         HUGE_VAL
         double acos(double x);
         double asin(double x);
         double atan(double x);
         double atan2(double y, double x);
         double cos(double x);
         double sin(double x);
         double tan(double x);
         double cosh(double x);
         double sinh(double x);
         double tanh(double x);
         double exp(double x);
         double frexp(double value, int *exp);
         double ldexp(double x, int exp);
         double log(double x);
         double log10(double x);
         double modf(double value, double *iptr);
         double pow(double x, double y);
         double sqrt(double x);
         double ceil(double x);
         double fabs(double x);
         double floor(double x);
         double fmod(double x, double y);


==== NON-LOCAL JUMPS <setjmp.h>

         jmp_buf
         int setjmp(jmp_buf env);
         void longjmp(jmp_buf env, int val);


==== SIGNAL HANDLING <signal.h>

         sig_atomic_t
     x    SIG_DFL
     x    SIG_ERR
     x    SIG_IGN
     x    SIGABRT
     x    SIGFPE
     x    SIGILL
     x    SIGINT
     x    SIGSEGV
     x    SIGTERM
     x    void (*signal(int sig, void (*func)(int)))(int);
     x    int raise(int sig);


==== VARIABLE ARGUMENTS <stdarg.h> x

     x    va_list
     x    void va_start(va_list ap,  parmN);
     x     type va_arg(va_list ap,  type);
     x    void va_end(va_list ap);


==== INPUT/OUTPUT <stdio.h>

         _IOFBF
         _IOLBF
         _IONBF
     x    BUFSIZ 
     x    EOF
     x    FILE
         FILENAME_MAX
     x    FOPEN_MAX
         fpos_t
         L_tmpnam
     x    NULL
     x    SEEK_CUR
     x    SEEK_END
     x    SEEK_SET
     x    size_t
     x    stderr
     x    stdin
     x    stdout
         TMP_MAX
     x    int remove(const char *filename);
     x    int rename(const char *old, const char *new);
         FILE *tmpfile(void);
         char *tmpnam(char *s);
     x    int fclose(FILE *stream);
     x    int fflush(FILE *stream);
     x    FILE *fopen(const char *filename, const char *mode);
     x    FILE *freopen(const char *filename, const char *mode,
                  FILE *stream);
     x    void setbuf(FILE *stream, char *buf);
     x    int setvbuf(FILE *stream, char *buf, int mode, size_t size);
     x    int fprintf(FILE *stream, const char *format, ...);
         int fscanf(FILE *stream, const char *format, ...);
     x    int printf(const char *format, ...);
         int scanf(const char *format, ...);
     x    int sprintf(char *s, const char *format, ...);
         int sscanf(const char *s, const char *format, ...);
     x    int vfprintf(FILE *stream, const char *format, va_list arg);
     x    int vprintf(const char *format, va_list arg);
         int vsprintf(char *s, const char *format, va_list arg);
     x    int fgetc(FILE *stream);
     x    char *fgets(char *s, int n, FILE *stream);
     x    int fputc(int c, FILE *stream);
     x    int fputs(const char *s, FILE *stream);
     x    int getc(FILE *stream);
     x    int getchar(void);
     x    char *gets(char *s);
     x    int putc(int c, FILE *stream);
     x    int putchar(int c);
     x    int puts(const char *s);
     x    int ungetc(int c, FILE *stream);
     x    size_t fread(void *ptr, size_t size, size_t nmemb,
                  FILE *stream);
     x    size_t fwrite(const void *ptr, size_t size, size_t nmemb,
                  FILE *stream);
     x    int fgetpos(FILE *stream, fpos_t *pos);
     x    int fseek(FILE *stream, long int offset, int whence);
     x    int fsetpos(FILE *stream, const fpos_t *pos);
     x    long int ftell(FILE *stream);
     x    void rewind(FILE *stream);
     x    void clearerr(FILE *stream);
     x    int feof(FILE *stream);
     x    int ferror(FILE *stream);
     x    void perror(const char *s);


==== GENERAL UTILITIES <stdlib.h>

     x    EXIT_FAILURE
     x    EXIT_SUCCESS
         MB_CUR_MAX
     x    NULL
         RAND_MAX
     x    div_t
     x    ldiv_t
     x    size_t
     x    wchar_t
         double atof(const char *nptr);
     x    int atoi(const char *nptr);
     x    long int atol(const char *nptr);
         double strtod(const char *nptr, char **endptr);
     x    long int strtol(const char *nptr, char **endptr, int base);
         unsigned long int strtoul(const char *nptr, char **endptr,
                  int base);
     x    int rand(void);
     x    void srand(unsigned int seed);
         void *calloc(size_t nmemb, size_t size);
     x    void free(void *ptr);
     x    void *malloc(size_t size);
     x    void *realloc(void *ptr, size_t size);
     x    void abort(void);
     x    int atexit(void (*func)(void));
     x    void exit(int status);
     x    char *getenv(const char *name);
     x    int system(const char *string);
         void *bsearch(const void *key, const void *base,
                  size_t nmemb, size_t size,
                  int (*compar)(const void *, const void *));
         void qsort(void *base, size_t nmemb, size_t size,
                  int (*compar)(const void *, const void *));
     x    int abs(int j);
     x    div_t div(int numer, int denom);
     x    long int labs(long int j);
     x    ldiv_t ldiv(long int numer, long int denom);
         int mblen(const char *s, size_t n);
         int mbtowc(wchar_t *pwc, const char *s, size_t n);
         int wctomb(char *s, wchar_t wchar);
         size_t mbstowcs(wchar_t *pwcs, const char *s, size_t n);
         size_t wcstombs(char *s, const wchar_t *pwcs, size_t n);



==== STRING HANDLING <string.h>

     x    NULL
     x    size_t
     x    void *memcpy(void *s1, const void *s2, size_t n);
     x    void *memmove(void *s1, const void *s2, size_t n);
     x    char *strcpy(char *s1, const char *s2);
     x    char *strncpy(char *s1, const char *s2, size_t n);
     x    char *strcat(char *s1, const char *s2);
     x    char *strncat(char *s1, const char *s2, size_t n);
     x    int memcmp(const void *s1, const void *s2, size_t n);
     x    int strcmp(const char *s1, const char *s2);
         int strcoll(const char *s1, const char *s2);
     x    int strncmp(const char *s1, const char *s2, size_t n);
         size_t strxfrm(char *s1, const char *s2, size_t n);
         void *memchr(const void *s, int c, size_t n);
     x    char *strchr(const char *s, int c);
         size_t strcspn(const char *s1, const char *s2);
         char *strpbrk(const char *s1, const char *s2);
     x    char *strrchr(const char *s, int c);
         size_t strspn(const char *s1, const char *s2);
     x    char *strstr(const char *s1, const char *s2);
         char *strtok(char *s1, const char *s2);
     x    void *memset(void *s, int c, size_t n);
     x    char *strerror(int errnum);
     x    size_t strlen(const char *s);


==== DATE AND TIME <time.h>

         CLK_TCK
      x   NULL
         clock_t
      x   time_t
      x   size_t
         struct tm
         clock_t clock(void);
         double difftime(time_t time1, time_t time0);
         time_t mktime(struct tm *timeptr);
      x   time_t time(time_t *timer);
         char *asctime(const struct tm *timeptr);
         char *ctime(const time_t *timer);
         struct tm *gmtime(const time_t *timer);
      x   struct tm *localtime(const time_t *timer);
         size_t strftime(char *s, size_t maxsize,
                  const char *format, const struct tm *timeptr);


=== defs

==== limits.h
         #define CHAR_BIT                         8
         #define CHAR_MAX    UCHAR_MAX  or SCHAR_MAX
         #define CHAR_MIN            0  or SCHAR_MIN
         #define MB_LEN_MAX                       1
         #define INT_MAX                     +32767
         #define INT_MIN                     -32767
         #define LONG_MAX               +2147483647
         #define LONG_MIN               -2147483647
         #define SCHAR_MAX                     +127
         #define SCHAR_MIN                     -127
         #define SHRT_MAX                    +32767
         #define SHRT_MIN                    -32767
         #define UCHAR_MAX                      255
         #define UINT_MAX                     65535
         #define ULONG_MAX               4294967295
         #define USHRT_MAX                    65535


==== float.h

         #define DBL_DIG                         10
         #define DBL_EPSILON                   1E-9
         #define DBL_MANT_DIG
         #define DBL_MAX                      1E+37
         #define DBL_MAX_10_EXP                 +37
         #define DBL_MAX_EXP
         #define DBL_MIN                      1E-37
         #define DBL_MIN_10_EXP                 -37
         #define DBL_MIN_EXP
         #define FLT_DIG                          6
         #define FLT_EPSILON                   1E-5
         #define FLT_MANT_DIG
         #define FLT_MAX                      1E+37
         #define FLT_MAX_10_EXP                 +37
         #define FLT_MAX_EXP
         #define FLT_MIN                      1E-37
         #define FLT_MIN_10_EXP                 -37
         #define FLT_MIN_EXP
         #define FLT_RADIX                        2
         #define FLT_ROUNDS
         #define LDBL_DIG                        10
         #define LDBL_EPSILON                  1E-9
         #define LDBL_MANT_DIG
         #define LDBL_MAX                     1E+37
         #define LDBL_MAX_10_EXP                +37
         #define LDBL_MAX_EXP
         #define LDBL_MIN                     1E-37
         #define LDBL_MIN_10_EXP                -37
         #define LDBL_MIN_EXP



