//+include

#define ERRNO_MAX 133



//+doc verbose error (errno) string. 
// this adds about 3.5kB to the compiled binary(!)
// Trying to shrink that here.
//+def
static const char* verbose_errstr2(int num){
		if ( num > ERRNO_MAX || num < 0 ){
				return("Errno unknown");
		}
		char *errstr = 
"Internal error (errno=0)\0"
"Operation not permitted\0"
"No such file or directory\0"
"No such process\0"
"Interrupted system call\0"
"I/O error\0"
"No such device or address\0"
"Argument list too long\0"
"Exec format error\0"
"Bad file number\0"
"No child processes\0"
"Try again\0"
"Out of memory\0"
"Permission denied\0"
"Bad address\0"
"Block device required\0"
"Device or resource busy\0"
"File exists\0"
"Cross-device link\0"
"No such device\0"
"Not a directory\0"
"Is a directory\0"
"Invalid argument\0"
"File table overflow\0"
"Too many open files\0"
"Not a typewriter\0"
"Text file busy\0"
"File too large\0"
"No space left on device\0"
"Illegal seek\0"
"Read-only file system\0"
"Too many links\0"
"Broken pipe\0"
"Math argument out of domain of func\0"
"Math result not representable\0"
"Resource deadlock would occur\0"
"File name too long\0"
"No record locks available\0"
"Invalid system call number\0"
"Directory not empty\0"
"Too many symbolic links encountered\0"
"Operation would block\0"
"No message of desired type\0"
"Identifier removed\0"
"Channel number out of range\0"
"Level 2 not synchronized\0"
"Level 3 halted\0"
"Level 3 reset\0"
"Link number out of range\0"
"Protocol driver not attached\0"
"No CSI structure available\0"
"Level 2 halted\0"
"Invalid exchange\0"
"Invalid request descriptor\0"
"Exchange full\0"
"No anode\0"
"Invalid request code\0"
"Invalid slot\0"
"Resource deadlock would occur\0"
"Bad font file format\0"
"Device not a stream\0"
"No data available\0"
"Timer expired\0"
"Out of streams resources\0"
"Machine is not on the network\0"
"Package not installed\0"
"Object is remote\0"
"Link has been severed\0"
"Advertise error\0"
"Srmount error\0"
"Communication error on send\0"
"Protocol error\0"
"Multihop attempted\0"
"RFS specific error\0"
"Not a data message\0"
"Value too large for defined data type\0"
"Name not unique on network\0"
"File descriptor in bad state\0"
"Remote address changed\0"
"Can not access a needed shared library\0"
"Accessing a corrupted shared library\0"
".lib section in a.out corrupted\0"
"Attempting to link in too many shared libraries\0"
"Cannot exec a shared library directly\0"
"Illegal byte sequence\0"
"Interrupted system call should be restarted\0"
"Streams pipe error\0"
"Too many users\0"
"Socket operation on non-socket\0"
"Destination address required\0"
"Message too long\0"
"Protocol wrong type for socket\0"
"Protocol not available\0"
"Protocol not supported\0"
"Socket type not supported\0"
"Operation not supported on transport endpoint\0"
"Protocol family not supported\0"
"Address family not supported by protocol\0"
"Address already in use\0"
"Cannot assign requested address\0"
"Network is down\0"
"Network is unreachable\0"
"Network dropped connection because of reset\0"
"Software caused connection abort\0"
"Connection reset by peer\0"
"No buffer space available\0"
"Transport endpoint is already connected\0"
"Transport endpoint is not connected\0"
"Cannot send after transport endpoint shutdown\0"
"Too many references: cannot splice\0"
"Connection timed out\0"
"Connection refused\0"
"Host is down\0"
"No route to host\0"
"Operation already in progress\0"
"Operation now in progress\0"
"Stale file handle\0"
"Structure needs cleaning\0"
"Not a XENIX named type file\0"
"No XENIX semaphores available\0"
"Is a named type file\0"
"Remote I/O error\0"
"Quota exceeded\0"
"No medium found\0"
"Wrong medium type\0"
"Operation Canceled\0"
"Required key not available\0"
"Key has expired\0"
"Key has been revoked\0"
"Key was rejected by service\0"
"Owner died\0"
"State not recoverable\0"
"Operation not possible due to RF-kill\0"
"Memory page has hardware error";
		char *c = errstr;
		
for ( ; num > 0; num-- ){
		do {
				c++;
		} while ( *c != 0 );
}
c++;
return(c);
}
