//#include	"arraymy.h"
//#include	"minishell1.h"
//#include	"stringmy.h"
#include	<fcntl.h>
#include	<signal.h>
#include	<stdio.h>
#include	<stdlib.h>
#include	<sys/stat.h>
#include	<sys/types.h>
#include	<sys/wait.h>
#include	<unistd.h>
#include "minilib.h"
//#include "stringmy.h"
